name: "Deploy frontend to firebase"
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn 

      - name: Build frontend
        run: yarn build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]  # Depend on 'build' and 'test' jobs
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn 

      - name: Build frontend
        run: yarn build

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  # sonarqube:
  #   runs-on: ubuntu-latest
  #   needs: deploy  # Depend on 'deploy' job
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v2

  #     - name: Install SonarQube Scanner
  #       run: |
  #         curl -L -o sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
  #         unzip sonar-scanner.zip
  #         export PATH=$PWD/sonar-scanner-4.6.2.2472-linux/bin:$PATH
  #       shell: bash

  #     - name: SonarQube Analysis
  #       run: sonar-scanner
  #       env:
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
